#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2023 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg@outlook.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    automatic_update = true
    autocomplete_method = "coc.nvim"
    bootstrap_before = 'myspacevim#before'
    bootstrap_after = 'myspacevim#after'
    colorscheme = "onedark"
    colorscheme_bg = "dark"
    disabled_plugins = []
    enable_filetree_gitstatus = true
    enable_guicolors = true
    enable_statusline_mode = true
    filemanager = "neo-tree"
    filetree_direction = "float"
    guifont = "FiraCode Nerd Font Mono:h16"
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_iseparator = "bar"
    statusline_separator = "arrow"
  # 状态栏左端部分的构成
    statusline_left_sections = ['winnr', 'major mode', 'filename', 'fileformat', 'minor mode lighters', 'version control info', 'search status']
    # 状态栏右端部分的构成
    statusline_right_sections = ['cursorpos', 'input method']
    buffer_index_type = 4
    enable_statusline_mode = false
    enable_tabline_filetype_icon = true
    vim_help_language = "cn"

[[layers]]
name = "VersionControl"

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "smar"
auto_completion_tab_key_behavior = "cycle"
auto_completion_delay = 200
auto_completion_complete_with_key_sequence = "nil"

[[layers]]
name = "checkers"
lint_on_the_fly = true
open_error_list = 2

[[layers]]
name = "chinese"

[[layers]]
name = "colorscheme"

[[layers]]
name = "core"
filetree_show_hidden = true

[[layers]]
name = "ctrlp"

[[layers]]
name = "debug"

[[layers]]
name = "default"

[[layers]]
name = "denite"

[[layers]]
name = 'edit'
autosave_all_buffers = true
autosave_timeout = 3000
autosave_location = '~/.cache/SpaceVim/autosave'

[[layers]]
name = "floobits"

[[layers]]
name = "foldsearch"

[[layers]]
name = "format"
format_on_save = true

[[layers]]
  name = "fzf"

[[layers]]
  name = "git"

[[layers]]
  name = "github"

[[layers]]
  name = "gtags"
  gtagslabel = "ctags"

[[layers]]
name = "lsp"
filetypes = ["css", "html", "javascript", "javascriptreact", "python", "rust", "sh", "typescript", "typescriptreact", "vim", "vue"]
enabled_clients = ['vimls']

[[layers]]
  name = "leaderf"

[[layers]]
  name = "shell"
  default_position = "bottom"

[[layers]]
  name = "ssh"
    # ssh_user = 'root'
    # ssh_address = '192.168.1.10'
    # ssh_port = '8097'

[[layers]]
  name = "sudo"

[[layers]]
name = "test"

[[layers]]
  name = "tools"

[[layers]]
  name = "treesitter"

[[layers]]
name = "ui"
enable_sidebar = true
enable_scrollbar = true
enable_cursorword = true

[[layers]]
  name = "unite"



[[layers]]
name = "core#banner"


[[layers]]
name = "core#statusline"
major_mode_cache = false

[[layers]]
name = "core#tabline"

[[layers]]
name = "lang#WebAssembly"

[[layers]]
  name = "lang#dockerfile"

[[layers]]
name = "lang#html"
# emmet_leader_key = "<C-e>"
emmet_filetyps = ['html']

[[layers]]
name = "lang#javascript"

[[layers]]
name = "lang#lua"

[[layers]]
name = "lang#markdown"
enableWcwidth = true
enabled_formatters = ["prettier"]

[[layers]]
name = "lang#python"

[[layers]]
name = "lang#rust"
recommended_style = true

[[layers]]
name = "lang#sh"

[[layers]]
name = "langtoml"

[[layers]]
  name = "lang#typescript"

[[layers]]
  name = "lang#vim"
auto_generate_doc = true

[[layers]]
name = "lang#vue"

[[layers]]
name = "tools#cpicker"

[[layers]]
name = "incsearch"

[[layers]]
name = "telescope"

